## 2025-09-24

### Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.3'

In [9]:
L = range(1000)
%timeit L2 = [i**2 for i in L]

102 μs ± 25.2 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [7]:
arr = np.arange(1000)
%timeit arr2 = arr**2

1.85 μs ± 412 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3]])
arr3 =

In [22]:
a=np.array([1,2,np.nan])
b=np.array([4,5,6])
a+b

array([ 5.,  7., nan])

In [23]:
b==4

array([ True, False, False])

In [25]:
a = [[0,1,2], [3,4,5]]

print(a[0][:2])

[0, 1]


In [26]:
print(a[1][1:])

[4, 5]


In [34]:
print(a[0][1])

1


In [35]:
[a[0][1], a[1][1]]

[1, 4]

In [37]:
blist = np.array([[0,1,2],[3,4,5]])
blist

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
blist.reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [44]:
blist[0, :2]

array([0, 1])

In [48]:
blist[1, 1:]

array([4, 5])

In [49]:
blist[:, 1]

array([1, 4])

In [51]:
blist[[0,1],[1,1]]

array([1, 4])

In [52]:
a=np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [53]:
a[0, :3]

array([0, 1, 2])

In [54]:
a[:,1]

array([1, 5])

In [58]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [59]:
clist = np.array([[0,1,2,4],[5,6,7,8],[9,10,11,12]])
clist

array([[ 0,  1,  2,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
clist[:,1:3]

array([[ 1,  2],
       [ 6,  7],
       [10, 11]])

In [61]:
clist[1,:]

array([5, 6, 7, 8])

In [63]:
clist[:, 2].reshape(3,1)

array([[ 2],
       [ 7],
       [11]])

In [64]:
clist[:,-2:-1]

array([[ 2],
       [ 7],
       [11]])

In [ ]:
#필터링 
a=np.array([1,2,3,4,5,6,7,8,9])
a[[2,3,4]]

array([3, 4, 5])

In [67]:
clist[[0,1,2],[2,0,1]]

array([ 2,  5, 10])

In [72]:
a=np.array([0,1,2,3,4,5,6,7,8,9])

a[a % 2 ==0]

array([0, 2, 4, 6, 8])

In [73]:
clist[clist%2==0]

array([ 0,  2,  4,  6,  8, 10, 12])

In [75]:
a[[0,0,4,0,0]]

array([0, 0, 4, 0, 0])

In [77]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
a[:,[0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [89]:
a[:,[True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [95]:
a[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
a[[2,0,1]]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [97]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [98]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [99]:
np.sum(a)

np.int64(78)

In [100]:
np.mean(a)

np.float64(6.5)

In [101]:
np.std(a)

np.float64(3.452052529534663)

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
x[ x % 3 == 0]



array([ 3,  6,  9, 12, 15, 18])

In [106]:
x[ x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [112]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

## pandas 시작

In [113]:
pip install pandas

   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.3/11.3 MB 8.3 MB/s eta 0:00:02
   -- ------------------------------------- 0.8/11.3 MB 12.1 MB/s eta 0:00:01
   ----- ---------------------------------- 1.5/11.3 MB 11.8 MB/s eta 0:00:01
   ------- -------------------------------- 2.0/11.3 MB 11.7 MB/s eta 0:00:01
   -------- ------------------------------- 2.5/11.3 MB 11.6 MB/s eta 0:00:01
   ---------- ----------------------------- 3.0/11.3 MB 11.3 MB/s eta 0:00:01
   ----------- ---------------------------- 3.4/11.3 MB 10.7 MB/s eta 0:00:01
   ------------- -------------------------- 3.9/11.3 MB 10.8 MB/s eta 0:00:01
   --------------- ------------------------ 4.4/11.3 MB 10.7 MB/s eta 0:00:01
   ----------------- ---------------------- 4.8/11.3 MB 10.7 MB/s eta 0:00:01
   ------------------ --------------------- 5.3/11.3 MB 10.5 MB/s eta 0:00:01
   -------------------- ------------------- 5.8/11.3 MB 10.7 MB/s eta 0:0


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [114]:
import pandas as pd

In [232]:
df = pd.read_csv("heroes.csv")
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [125]:
pd.options.display.float_format = '{:,.0f}'.format

In [126]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [127]:
df.describe()

나이   키                 재산
count   7   7                  5
mean   34 190  2,300,278,000,120
std    13  36  5,142,800,956,894
min    18 170                600
25%    26 172         50,000,000
50%    32 177        340,000,000
75%    39 184      1,000,000,000
max    58 270 11,500,000,000,000

In [132]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [134]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [164]:
df.nlargest(7, '키')

이름  나이     직업     국적    키                 재산
4     헐크  33  핵물리학자     미국  270      1,000,000,000
1     토르  45      신  아스가르드  190                NaN
3   원더우먼  27     공주  데미스키라  178                NaN
2  스파이더맨  18   고등학생     미국  177                600
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [ ]:
df.iloc[[1:4], [1:3]]

SyntaxError: invalid syntax (2695004669.py, line 1)

In [156]:
df.iloc[:4,:3]

이름  나이    직업
0   아이언맨  58   CEO
1     토르  45     신
2  스파이더맨  18  고등학생
3   원더우먼  27    공주

In [ ]:
df.loc[2:5]

이름  나이     직업     국적    키            재산
2  스파이더맨  18   고등학생     미국  177           600
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000
5   캡틴마블  25    파일럿     미국  170   340,000,000

In [172]:
df[(df['나이']>30) & (df['나이']<50)]

이름  나이     직업     국적    키            재산
1     토르  45      신  아스가르드  190           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000
6  블랙위도우  32    스파이    러시아  170    50,000,000

In [179]:
df.loc[:3, '나이':'국적']

나이    직업     국적
0  58   CEO     미국
1  45     신  아스가르드
2  18  고등학생     미국
3  27    공주  데미스키라

In [192]:
df.loc[df['키'] >= 180, ['이름', '나이']]

이름  나이
1  토르  45
4  헐크  33

In [191]:
df.loc[df['키'] >= 180, '이름':'키']

이름  나이     직업     국적    키
1  토르  45      신  아스가르드  190
4  헐크  33  핵물리학자     미국  270

In [210]:
df['전투력'] = 99

In [211]:
df

이름  나이     직업     국적    키                 재산  전투력
0   아이언맨  58    CEO     미국  174 11,500,000,000,000   99
1     토르  45      신  아스가르드  190                NaN   99
2  스파이더맨  18   고등학생     미국  177                600   99
3   원더우먼  27     공주  데미스키라  178                NaN   99
4     헐크  33  핵물리학자     미국  270      1,000,000,000   99
5   캡틴마블  25    파일럿     미국  170        340,000,000   99
6  블랙위도우  32    스파이    러시아  170         50,000,000   99

In [213]:
df.drop(columns=['전투력'], inplace = True)

In [214]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [6]:
df.isnull()

이름     나이     직업     국적      키     재산
0  False  False  False  False  False  False
1  False  False  False  False  False   True
2  False  False  False  False  False  False
3  False  False  False  False  False   True
4  False  False  False  False  False  False
5  False  False  False  False  False  False
6  False  False  False  False  False  False

In [218]:
df.dropna(inplace = True)

In [219]:
df

이름  나이     직업   국적    키                 재산
0   아이언맨  58    CEO   미국  174 11,500,000,000,000
2  스파이더맨  18   고등학생   미국  177                600
4     헐크  33  핵물리학자   미국  270      1,000,000,000
5   캡틴마블  25    파일럿   미국  170        340,000,000
6  블랙위도우  32    스파이  러시아  170         50,000,000

In [222]:
df['재산'].isnull()

0    False
1     True
2    False
3     True
4    False
5    False
6    False
Name: 재산, dtype: bool

In [224]:
df.isnull()

이름     나이     직업     국적      키     재산
0  False  False  False  False  False  False
1  False  False  False  False  False   True
2  False  False  False  False  False  False
3  False  False  False  False  False   True
4  False  False  False  False  False  False
5  False  False  False  False  False  False
6  False  False  False  False  False  False

In [225]:
df.isnull().sum()

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64

In [230]:
df['재산'].fillna(df['재산'].mean())

0   11,500,000,000,000
1    2,300,278,000,120
2                  600
3    2,300,278,000,120
4        1,000,000,000
5          340,000,000
6           50,000,000
Name: 재산, dtype: float64

In [233]:
df.fillna(method='ffill')

C:\Users\USER\AppData\Local\Temp\ipykernel_8096\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190 11,500,000,000,000
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                600
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [234]:
df.iloc[5, 1] = np.nan

In [ ]:
df['나이']=df['나이'].fillna(df['나이'].mean())

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('heroes.csv')

In [275]:
df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

In [273]:
def add_cm(height):
    return str(height)+'cm'

df['키'] = df['키'].apply(add_cm)

In [252]:
df

이름  나이     직업     국적      키                 재산
0   아이언맨  58    CEO     미국  174cm 11,500,000,000,000
1     토르  45      신  아스가르드  190cm                NaN
2  스파이더맨  18   고등학생     미국  177cm                600
3   원더우먼  27     공주  데미스키라  178cm                NaN
4     헐크  33  핵물리학자     미국  270cm      1,000,000,000
5   캡틴마블  25    파일럿     미국  170cm        340,000,000
6  블랙위도우  32    스파이    러시아  170cm         50,000,000

In [262]:
def add_name(height):
    return '닥터지바고'

df.loc[0, '이름'] = df.loc[0, '이름'].apply(add_name)

AttributeError: 'str' object has no attribute 'apply'

In [277]:
df['키'] = df['키'].apply(lambda x: str(x)+'mm')


In [278]:
df

이름  나이     직업     국적      키                 재산
0   아이언맨  58    CEO     미국  174mm 11,500,000,000,000
1     토르  45      신  아스가르드  190mm                NaN
2  스파이더맨  18   고등학생     미국  177mm                600
3   원더우먼  27     공주  데미스키라  178mm                NaN
4     헐크  33  핵물리학자     미국  270mm      1,000,000,000
5   캡틴마블  25    파일럿     미국  170mm        340,000,000
6  블랙위도우  32    스파이    러시아  170mm         50,000,000

In [281]:
df.groupby('국적')['키'].mean()

TypeError: agg function failed [how->mean,dtype->object]